name: Continuous Integration

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: ['*']
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Build and Test
    strategy:
      matrix:
        os: [ubuntu-latest]
        scala: [3.1.3]
        java: [ openjdk@1.17 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java and Scala
        uses: olafurpg/setup-scala@v11
        with:
          java-version: ${{ matrix.java }}

      #      - name: Set docker options
      #        run: |
      #          mkdir ~/docker_dir
      #          echo "DOCKER_OPTS="-g ~/docker_dir"" >> $GITHUB_ENV
      #
      #      - name: Cache docker
      #        uses: actions/cache@v2
      #        with:
      #          path: |
      #            ~/docker_dir
      #          key: docker

      - name: Cache sbt
        uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier/cache/v1
            ~/.cache/coursier/v1
            ~/AppData/Local/Coursier/Cache/v1
            ~/Library/Caches/Coursier/v1
          key: ${{ runner.os }}-sbt-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}

      - name: Start redis
        run: bin/redis.sh start

      - name: Test project
        run: sbt ++${{ matrix.scala }} test