name: Continuous Integration

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: ['*']
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Build and Test
    strategy:
      matrix:
        os: [ubuntu-latest]
        scala: [ 3.3.4 ]
        java: [ openjdk@1.21 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: coursier/setup-action@v1
        with:
          jvm: zulu:21.0.2

      #      - name: Set docker options
      #        run: |
      #          mkdir ~/docker_dir
      #          echo "DOCKER_OPTS="-g ~/docker_dir"" >> $GITHUB_ENV
      #
      #      - name: Cache docker
      #        uses: actions/cache@v2
      #        with:
      #          path: |
      #            ~/docker_dir
      #          key: docker

      - name: Cache sbt
        uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier/cache/v1
            ~/.cache/coursier/v1
            ~/AppData/Local/Coursier/Cache/v1
            ~/Library/Caches/Coursier/v1
          key: ${{ runner.os }}-sbt-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}

      - name: Start redis
        run: bin/redis.sh start

      - name: Test project
        run: sbt ++${{ matrix.scala }} test
